/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:9820e470-c4f2-40ea-9a9f-44acd2810c7e",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_DvmBugfKU",
    "aws_user_pools_web_client_id": "30oa7o7tfisoaa7thbpi58ps3p",
    "oauth": {}
};


export default awsmobile;
