/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:9820e470-c4f2-40ea-9a9f-44acd2810c7e",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_DvmBugfKU",
    "aws_user_pools_web_client_id": "30oa7o7tfisoaa7thbpi58ps3p",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://jf7othrasfat7i4ztymoachh4a.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-gpz2dtwoszhi7fccnen5zjc7gy",
    "aws_user_files_s3_bucket": "amplifyapp114817-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
